---
title: "Schedule"
format:
    html: default
    #pdf: default
---

- **L**: Watch lecture videos and respond to survey by **Wednesday at 8pm**.

- **H**: Homework assignments are due by the **end of Sunday (midnight)**.

- **Final project**  
  - **Data**: Description of data due by June 1  
  - **Proposal**: Proposal of final project due by July 6  
  - **Presentation**: Presentation in class on August 21  
  - **Paper**: Final paper due by August 24  

Week	  | Date          |	Topic	                        |	L	    |	H	    |
|:------|:--------------|:------------------------------|:------|:------|
1	    |	May 08    	|	Introduction, R, markdown	        |	1	    |		|
2	    |	May 15*	    |	Data manipulation	                |	2	    |	1	|
3	    |	May 22	    |	Samples, sampling distribution	  |	3	    |	2	|
4	    |	May 29*	    |	NO CLASS	                        |	 	    |	Data	|
5	    |	June 05	    |	ggplot	                          |	4	    |	 	|
6	    |	June 12	    |	ggplot	                          |	5	    |	3 |
7	    |	June 19	    |	Linear regression                 |	6	    |	 	|
8	    |	June 26	    |	Linear regression         	      |	7	    |	4	|
9	    |	July 03*	  |	NO CLASS             	            |		    |	Proposal	|
10	  |	July 10	    |	Linear regression	                |	8	    |		|
11	  |	July 17	    |	Linear regression   	            |	9	    |	5	|
12	  |	July 24	    |	Linear regression   	            |	10	  |	 	|
13	  |	July 31	    |	Linear regression   	            |	11	  |	6	|
14	  |	August 07   |	Logistic regression               |	12	  |	7	|
15	  |	August 14*	|	Poisson regression                |	13	  |	8	|
16	  |	August 21	  |	Presentations	                    |		    | Final	| 

* Adjusted days  
  * May 15: Late start 
  * May 29: Holiday / Stefany at conference  
  * July 3: Holiday  
  * August 14: Late start  

- **All due dates subject to change** due to weather, emergency, scheduling changes, etc. 

